Update autopkgtests to show a relevant "diffoscope" result on failure

diff --git a/debian/tests/stretch b/debian/tests/stretch
--- a/debian/tests/stretch
+++ b/debian/tests/stretch
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 
+# see https://people.debian.org/~tianon/debuerreotype/
+
 suite='stretch'
 timestamp='2017-01-01T00:00:00Z'
 
 expectedEpoch='1483228800'
-expectedSha256='426b8ef5a40588c61084cafbb5a187e6a8e1089da34821f314ea3369f90c8931'
+expectedSha256='2839acd297e012d00683008af92e35e17e3f3b6eb0c4910e3d545f4f8e0ca450'
 
-rootfs="$(mktemp -d)"
-trap "rm -rf '$rootfs'" EXIT
+tempDir="$(mktemp -d)"
+trap "rm -rf '$tempDir'" EXIT
+rootfs="$tempDir/rootfs"
 
 set -x
 
@@ -19,5 +22,20 @@ debuerreotype-chroot "$rootfs" true
 
 debuerreotype-gen-sources-list "$rootfs" "$suite" http://deb.debian.org/debian http://security.debian.org
 
-sha256="$(debuerreotype-tar "$rootfs" - | sha256sum | cut -d' ' -f1)"
-[ "$sha256" = "$expectedSha256" ]
+debuerreotype-tar "$rootfs" "$tempDir/actual.tar"
+sha256="$(sha256sum "$tempDir/actual.tar" | cut -d' ' -f1)"
+
+if [ "$sha256" != "$expectedSha256" ]; then
+	(
+		set +x
+		echo >&2
+		echo >&2 'ERROR: expected SHA256 does not match actual -- downloading pristine source to compare (via diffoscope)'
+		echo >&2
+	)
+
+	toCompare="https://people.debian.org/~tianon/debuerreotype/$suite--$timestamp--$expectedSha256.txz"
+	wget -qO "$tempDir/expected.txz" "$toCompare"
+	xz -d < "$tempDir/expected.txz" > "$tempDir/expected.tar"
+	diffoscope >&2 "$tempDir/expected.tar" "$tempDir/actual.tar"
+	exit 1
+fi
